### PR TITLE
feat: if not found cmd in other language, tried to locate in English …

### PR DESCRIPTION
**Pull request by LiuZengqiang**
feat:
1. If not found a command in any other language, tried to locate it in English. 
For example, ``LANG=zh tldr bc`` will not find bc.md in directory ``pages.zh/*``, but the file ``bc.md`` does exist in directory ``pages/*``. It can help user find the command description in English version.
3. Add timeout limit for downloading (curl of wget), default timeout limit is 10 second.

### CODE REVIEW

**Comment by LiuZengqiang** [comment]
There are some bugs.

**Comment by LiuZengqiang** [comment]
Have been fixed.

**Review by pepa65 — COMMENTED** [review]
Thank you for working on this. I had some code formatting issues with the last part, so I made the changes manually, but all praise to your work!

**Comment by LiuZengqiang** [comment]
: )

**Pull request closed without merging**
